// GENERATED by tool/build_icon_fonts.py — do not edit by hand.
//
// Material Symbols Rounded (Apache 2.0), weight 400, optical size 24,
// as static fonts: `WpIcons.x` is unfilled, `WpIcons.filled(x)` its
// filled form (D-21).
import 'package:flutter/widgets.dart';

abstract final class WpIcons {
  static const accountTree = IconData(0xe97a, fontFamily: 'WpSymbols');
  static const add = IconData(0xe145, fontFamily: 'WpSymbols');
  static const altRoute = IconData(0xf184, fontFamily: 'WpSymbols');
  static const checkCircle = IconData(0xe86c, fontFamily: 'WpSymbols');
  static const chevronLeft = IconData(0xe408, fontFamily: 'WpSymbols');
  static const chevronRight = IconData(0xe409, fontFamily: 'WpSymbols');
  static const clockLoader40 = IconData(0xf724, fontFamily: 'WpSymbols');
  static const close = IconData(0xe14c, fontFamily: 'WpSymbols');
  static const delete = IconData(0xe872, fontFamily: 'WpSymbols');
  static const download = IconData(0xe171, fontFamily: 'WpSymbols');
  static const edit = IconData(0xe150, fontFamily: 'WpSymbols');
  static const editNote = IconData(0xe745, fontFamily: 'WpSymbols');
  static const error = IconData(0xe000, fontFamily: 'WpSymbols');
  static const expandMore = IconData(0xe5cf, fontFamily: 'WpSymbols');
  static const folder = IconData(0xe2c7, fontFamily: 'WpSymbols');
  static const folderCopy = IconData(0xebbd, fontFamily: 'WpSymbols');
  static const folderDelete = IconData(0xeb34, fontFamily: 'WpSymbols');
  static const folderOpen = IconData(0xe2c8, fontFamily: 'WpSymbols');
  static const history = IconData(0xe28e, fontFamily: 'WpSymbols');
  static const info = IconData(0xe88e, fontFamily: 'WpSymbols');
  static const keyboard = IconData(0xe312, fontFamily: 'WpSymbols');
  static const label = IconData(0xe892, fontFamily: 'WpSymbols');
  static const labelOff = IconData(0xe9b6, fontFamily: 'WpSymbols');
  static const leftPanelClose = IconData(0xf717, fontFamily: 'WpSymbols');
  static const leftPanelOpen = IconData(0xf716, fontFamily: 'WpSymbols');
  static const list = IconData(0xe896, fontFamily: 'WpSymbols');
  static const menu = IconData(0xe5d2, fontFamily: 'WpSymbols');
  static const menuBook = IconData(0xea19, fontFamily: 'WpSymbols');
  static const psychologyAlt = IconData(0xf8ea, fontFamily: 'WpSymbols');
  static const radioButtonUnchecked = IconData(0xe836, fontFamily: 'WpSymbols');
  static const remove = IconData(0xe15b, fontFamily: 'WpSymbols');
  static const school = IconData(0xe80c, fontFamily: 'WpSymbols');
  static const search = IconData(0xe8b6, fontFamily: 'WpSymbols');
  static const sell = IconData(0xe54e, fontFamily: 'WpSymbols');
  static const sentimentDissatisfied = IconData(
    0xe811,
    fontFamily: 'WpSymbols',
  );
  static const sentimentNeutral = IconData(0xe812, fontFamily: 'WpSymbols');
  static const sentimentSatisfied = IconData(0xe0ed, fontFamily: 'WpSymbols');
  static const settings = IconData(0xe8b8, fontFamily: 'WpSymbols');
  static const settingsBackupRestore = IconData(
    0xe8ba,
    fontFamily: 'WpSymbols',
  );
  static const stacks = IconData(0xf500, fontFamily: 'WpSymbols');
  static const style = IconData(0xe41d, fontFamily: 'WpSymbols');
  static const swapHoriz = IconData(0xe8d4, fontFamily: 'WpSymbols');
  static const taskAlt = IconData(0xe2e6, fontFamily: 'WpSymbols');
  static const uploadFile = IconData(0xe9fc, fontFamily: 'WpSymbols');
  static const swipe = IconData(0xe9ec, fontFamily: 'WpSymbols');
  static const viewModule = IconData(0xe8f0, fontFamily: 'WpSymbols');
  static const visibility = IconData(0xe417, fontFamily: 'WpSymbols');
  static const visibilityOff = IconData(0xe8f5, fontFamily: 'WpSymbols');
  static const warning = IconData(0xe002, fontFamily: 'WpSymbols');

  static const _filled = <int, IconData>{
    0xe97a: IconData(0xe97a, fontFamily: 'WpSymbolsFilled'),
    0xe145: IconData(0xe145, fontFamily: 'WpSymbolsFilled'),
    0xf184: IconData(0xf184, fontFamily: 'WpSymbolsFilled'),
    0xe86c: IconData(0xe86c, fontFamily: 'WpSymbolsFilled'),
    0xe408: IconData(0xe408, fontFamily: 'WpSymbolsFilled'),
    0xe409: IconData(0xe409, fontFamily: 'WpSymbolsFilled'),
    0xf724: IconData(0xf724, fontFamily: 'WpSymbolsFilled'),
    0xe14c: IconData(0xe14c, fontFamily: 'WpSymbolsFilled'),
    0xe872: IconData(0xe872, fontFamily: 'WpSymbolsFilled'),
    0xe171: IconData(0xe171, fontFamily: 'WpSymbolsFilled'),
    0xe150: IconData(0xe150, fontFamily: 'WpSymbolsFilled'),
    0xe745: IconData(0xe745, fontFamily: 'WpSymbolsFilled'),
    0xe000: IconData(0xe000, fontFamily: 'WpSymbolsFilled'),
    0xe5cf: IconData(0xe5cf, fontFamily: 'WpSymbolsFilled'),
    0xe2c7: IconData(0xe2c7, fontFamily: 'WpSymbolsFilled'),
    0xebbd: IconData(0xebbd, fontFamily: 'WpSymbolsFilled'),
    0xeb34: IconData(0xeb34, fontFamily: 'WpSymbolsFilled'),
    0xe2c8: IconData(0xe2c8, fontFamily: 'WpSymbolsFilled'),
    0xe28e: IconData(0xe28e, fontFamily: 'WpSymbolsFilled'),
    0xe88e: IconData(0xe88e, fontFamily: 'WpSymbolsFilled'),
    0xe312: IconData(0xe312, fontFamily: 'WpSymbolsFilled'),
    0xe892: IconData(0xe892, fontFamily: 'WpSymbolsFilled'),
    0xe9b6: IconData(0xe9b6, fontFamily: 'WpSymbolsFilled'),
    0xf717: IconData(0xf717, fontFamily: 'WpSymbolsFilled'),
    0xf716: IconData(0xf716, fontFamily: 'WpSymbolsFilled'),
    0xe896: IconData(0xe896, fontFamily: 'WpSymbolsFilled'),
    0xe5d2: IconData(0xe5d2, fontFamily: 'WpSymbolsFilled'),
    0xea19: IconData(0xea19, fontFamily: 'WpSymbolsFilled'),
    0xf8ea: IconData(0xf8ea, fontFamily: 'WpSymbolsFilled'),
    0xe836: IconData(0xe836, fontFamily: 'WpSymbolsFilled'),
    0xe15b: IconData(0xe15b, fontFamily: 'WpSymbolsFilled'),
    0xe80c: IconData(0xe80c, fontFamily: 'WpSymbolsFilled'),
    0xe8b6: IconData(0xe8b6, fontFamily: 'WpSymbolsFilled'),
    0xe54e: IconData(0xe54e, fontFamily: 'WpSymbolsFilled'),
    0xe811: IconData(0xe811, fontFamily: 'WpSymbolsFilled'),
    0xe812: IconData(0xe812, fontFamily: 'WpSymbolsFilled'),
    0xe0ed: IconData(0xe0ed, fontFamily: 'WpSymbolsFilled'),
    0xe8b8: IconData(0xe8b8, fontFamily: 'WpSymbolsFilled'),
    0xe8ba: IconData(0xe8ba, fontFamily: 'WpSymbolsFilled'),
    0xf500: IconData(0xf500, fontFamily: 'WpSymbolsFilled'),
    0xe41d: IconData(0xe41d, fontFamily: 'WpSymbolsFilled'),
    0xe8d4: IconData(0xe8d4, fontFamily: 'WpSymbolsFilled'),
    0xe2e6: IconData(0xe2e6, fontFamily: 'WpSymbolsFilled'),
    0xe9fc: IconData(0xe9fc, fontFamily: 'WpSymbolsFilled'),
    0xe9ec: IconData(0xe9ec, fontFamily: 'WpSymbolsFilled'),
    0xe8f0: IconData(0xe8f0, fontFamily: 'WpSymbolsFilled'),
    0xe417: IconData(0xe417, fontFamily: 'WpSymbolsFilled'),
    0xe8f5: IconData(0xe8f5, fontFamily: 'WpSymbolsFilled'),
    0xe002: IconData(0xe002, fontFamily: 'WpSymbolsFilled'),
  };

  /// The filled form of [icon] (one of the icons above).
  static IconData filled(IconData icon) => _filled[icon.codePoint]!;
}
