"""Builds the app's icon fonts and lib/ui/theme/wp_icons.dart (D-21).

Flutter's release-mode icon tree shaker corrupts the `gvar` table of variable
fonts, so the variable Material Symbols font lost glyphs in release builds.
This script cuts static fonts instead: Material Symbols Rounded pinned at
weight 400, grade 0, optical size 24, once unfilled (WpSymbols) and once
filled (WpSymbolsFilled), keeping only the icons listed below.

Needs Python 3 with fontTools (`pip install fonttools`) and the variable font
MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf from
https://github.com/google/material-design-icons/tree/master/variablefont
(Apache 2.0). Run from the project root:

    python tool/build_icon_fonts.py path/to/MaterialSymbolsRounded.ttf

Add an icon: append its Material Symbols name to ICONS, rerun, then
`dart format lib/ui/theme/wp_icons.dart`.
"""

import sys

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ICONS = """
account_tree add alt_route check_circle chevron_left chevron_right
clock_loader_40 close delete download edit edit_note error expand_more
folder folder_copy folder_delete folder_open history info keyboard label
label_off left_panel_close left_panel_open list menu menu_book
psychology_alt radio_button_unchecked remove school search sell
sentiment_dissatisfied sentiment_neutral sentiment_satisfied settings
settings_backup_restore stacks style swap_horiz task_alt upload_file
view_module visibility visibility_off warning
""".split()

FONTS = {'WpSymbols': 0, 'WpSymbolsFilled': 1}


def camel(name):
    head, *rest = name.split('_')
    return head + ''.join(p[:1].upper() + p[1:] for p in rest)


def main(source):
    font = TTFont(source)
    by_name = {}
    for cp, glyph in font.getBestCmap().items():
        if 0xE000 <= cp <= 0xF8FF:  # icons live in the Private Use Area
            by_name.setdefault(glyph, cp)
    missing = [n for n in ICONS if n not in by_name]
    if missing:
        sys.exit(f'not in the font: {missing}')
    codepoints = {n: by_name[n] for n in ICONS}

    for family, fill in FONTS.items():
        f = TTFont(source)
        opts = subset.Options()
        opts.layout_features = []  # no ligatures: icons are drawn by codepoint
        opts.name_IDs = ['*']
        opts.notdef_outline = True
        sub = subset.Subsetter(opts)
        sub.populate(unicodes=codepoints.values())
        sub.subset(f)
        f = instantiateVariableFont(
            f, {'FILL': fill, 'wght': 400, 'GRAD': 0, 'opsz': 24})
        f.save(f'assets/fonts/{family}.ttf')

    lines = [
        '// GENERATED by tool/build_icon_fonts.py — do not edit by hand.',
        '//',
        '// Material Symbols Rounded (Apache 2.0), weight 400, optical size 24,',
        '// as static fonts: `WpIcons.x` is unfilled, `WpIcons.filled(x)` its',
        '// filled form (D-21).',
        "import 'package:flutter/widgets.dart';",
        '',
        'abstract final class WpIcons {',
    ]
    for n in ICONS:
        lines.append(f'  static const {camel(n)} = IconData(0x{codepoints[n]:x}, '
                     "fontFamily: 'WpSymbols');")
    lines += ['', '  static const _filled = <int, IconData>{']
    for n in ICONS:
        lines.append(f'    0x{codepoints[n]:x}: IconData(0x{codepoints[n]:x}, '
                     "fontFamily: 'WpSymbolsFilled'),")
    lines += [
        '  };',
        '',
        '  /// The filled form of [icon] (one of the icons above).',
        '  static IconData filled(IconData icon) => _filled[icon.codePoint]!;',
        '}',
        '',
    ]
    with open('lib/ui/theme/wp_icons.dart', 'w', encoding='utf-8', newline='\n') as out:
        out.write('\n'.join(lines))
    print(f'{len(ICONS)} icons -> assets/fonts/WpSymbols*.ttf, lib/ui/theme/wp_icons.dart')


if __name__ == '__main__':
    main(sys.argv[1])
