// Embeds fixture files into integration_test/fixture_data.g.dart, because
// integration tests run on the device and cannot read fixtures/ from the host.
// Run after changing fixtures:  dart run tool/gen_fixture_data.dart
import 'dart:convert';
import 'dart:io';

const files = ['definitions.txt', 'edge-cases.txt'];

void main() {
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_fixture_data.dart. Do not edit.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln("import 'dart:convert';")
    ..writeln()
    ..writeln('/// Fixture file name → bytes (base64-encoded).')
    ..writeln('final fixtureBytes = <String, List<int>>{');
  for (final name in files) {
    final data = base64.encode(File('fixtures/$name').readAsBytesSync());
    out.writeln("  '$name': base64.decode(");
    out.writeln("    '$data',");
    out.writeln('  ),');
  }
  out.writeln('};');
  File('integration_test/fixture_data.g.dart').writeAsStringSync('$out');
}
